class SurroxError(Exception): ...


class ProblemDefinitionError(SurroxError): ...


class ConfigurationError(SurroxError): ...


class SurrogateTrainingError(SurroxError): ...


class OptimizationError(SurroxError): ...
